### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by sanjamkr** [arushibutan11/AMS#13]
- [x] Apply jquery on 'Other' text fields and display them only when Other is selected in drop down

- [x] Add New Fields - Details model: APZ Zone (Text)

- [ ] Add New Fields - Offending Vehicle:  License (Yes/No Dropdown), Type of License(Permanent/Learner),  Reason for no license(Minor/License not issued)

- [x] Remove first row header from db tables

- [x] Fix file upload error

- [x] Add and compute old fields that have to be maintained on the back end

- [x] Apply validations for FIR Date, Accident Date, Injured-Killed v/s Section selected, License Issue Date etc

- [x] Connect Drunken Driving to MVA Act

- [x] Sub Vehicle type (TWW)

**Comment by sanjamkr** [comment]
@DivyaSharma1974 
jQuery, row header, MVA act
@sanjamkr
Validations, file, old fields
@arushibutan11 
New fieldsx2, sub vehicle type

**Comment by arushibutan11** [comment]
@sanjamkr All license fields are not added.

**Comment by sanjamkr** [comment]
@arushibutan11 who cares
